volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  {%- if cookiecutter.cloud_provider == 'None' %}
  production_django_media: {}
  {%- endif %}
  {% if cookiecutter.use_celery == 'y' %}
  production_redis_data: {}
  {% endif %}


services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      {%- if cookiecutter.frontend_pipeline == 'Webpack' and cookiecutter.use_whitenoise == 'n' %}
      args:
        # These variable can be defined in an .env file in the root of the repo
        {%- if cookiecutter.cloud_provider == 'AWS' %}
        DJANGO_AWS_STORAGE_BUCKET_NAME: ${DJANGO_AWS_STORAGE_BUCKET_NAME}
        DJANGO_AWS_S3_CUSTOM_DOMAIN: ${DJANGO_AWS_S3_CUSTOM_DOMAIN}
        {%- elif cookiecutter.cloud_provider == 'GCP' %}
        DJANGO_GCP_STORAGE_BUCKET_NAME: ${DJANGO_GCP_STORAGE_BUCKET_NAME}
        {%- elif cookiecutter.cloud_provider == 'Azure' %}
        DJANGO_AZURE_ACCOUNT_NAME: ${DJANGO_AZURE_ACCOUNT_NAME}
        {%- endif %}
      {%- endif %}

    image: {{ cookiecutter.project_slug }}_production_django
    {%- if cookiecutter.cloud_provider == 'None' %}
    volumes:
      - production_django_media:/app/{{ cookiecutter.project_slug }}/media
    {%- endif %}
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    labels:
      - "traefik.enable=true"
      {%- if cookiecutter.domain_name.count('.') == 1 %}
      - "traefik.http.routers.django.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      {%- else %}
      - "traefik.http.routers.django.rule=Host(`${DOMAIN}`)"
      {%- endif %}
      - "traefik.http.routers.django.entrypoints=web-secure"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
      - "traefik.http.routers.django.middlewares=csrf"
      - "traefik.http.middlewares.csrf.headers.hostsProxyHeaders=X-CSRFToken"
      - "traefik.http.services.django.loadbalancer.server.port=5000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      {%- if cookiecutter.postgresql_version|int >= 18 %}
      - production_postgres_data:/var/lib/postgresql/{{ cookiecutter.postgresql_version }}/docker
      {%- else %}
      - production_postgres_data:/var/lib/postgresql/data
      {%- endif %}
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    image: docker.io/traefik:3.6
    depends_on:
      - django
    command:
      - "--log.level=INFO"
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=web-secure"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    volumes:
      - production_traefik:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    env_file:
      - ./.envs/.production/.traefik
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: docker.io/redis:7.2
    {% if cookiecutter.use_celery == 'y' %}
    volumes:
      - production_redis_data:/data
    {% endif %}


  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_celeryworker
    command: /start-celeryworker
    labels: []

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_celerybeat
    command: /start-celerybeat
    labels: []

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_production_flower
    command: /start-flower
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`${DOMAIN}`) && PathPrefix(`/flower`)"
      - "traefik.http.routers.flower.entrypoints=web-secure"
      - "traefik.http.routers.flower.tls.certresolver=letsencrypt"
      - "traefik.http.routers.flower.priority=200"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"
  {%- endif %}
  {%- if cookiecutter.cloud_provider == 'AWS' %}

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z
  {%- endif %}
  {%- if cookiecutter.cloud_provider == 'None' %}

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    labels:
      - "traefik.enable=true"
      {%- if cookiecutter.domain_name.count('.') == 1 %}
      - "traefik.http.routers.media.rule=(Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)) && PathPrefix(`/media/`)"
      {%- else %}
      - "traefik.http.routers.media.rule=Host(`${DOMAIN}`) && PathPrefix(`/media/`)"
      {%- endif %}
      - "traefik.http.routers.media.entrypoints=web-secure"
      - "traefik.http.routers.media.tls.certresolver=letsencrypt"
      - "traefik.http.routers.media.priority=200"
      - "traefik.http.services.media.loadbalancer.server.port=80"
  {%- endif %}
