export COMPOSE_FILE := "docker-compose.local.yml"

# Default command to list all available commands.
default:
    @just --list

# build: Build python image.
build:
    @echo "Building python image..."
    @docker-compose build

# up: Start up containers.
up:
    @echo "Starting up containers..."
    @docker-compose up -d --remove-orphans

# down: Stop containers.
down:
    @echo "Stopping containers..."
    @docker-compose down

# prune: Remove containers and their volumes.
prune *args:
    @echo "Killing containers and removing volumes..."
    @docker-compose down -v {{ "{{args}}" }}

# logs: View container logs
logs *args:
    @docker-compose logs -f {{ "{{args}}" }}

# manage: Executes `manage.py` command.
manage +args:
    @docker-compose run --rm django python ./manage.py {{ "{{args}}" }}
