version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_redis_data: {}
  production_caddy: {}

services:
  django:{% if cookiecutter.use_celery == 'y' %} &django{% endif %}
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        environment: production
        cmd: /django
    image: {{ cookiecutter.project_slug }}_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    command: /django
  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        environment: production
        cmd: /celeryworker
    image: {{ cookiecutter.project_slug }}_production_celeryworker
    ports: []
    command: /celeryworker

  celerybeat:
    <<: *django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        environment: production
        cmd: /celerybeat
    image: {{ cookiecutter.project_slug }}_production_celerybeat
    user: root  # TODO: a temporary workaround -- do it right instead
    command: /celerybeat

  flower:
    <<: *django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        environment: production
        cmd: /flower
    image: {{ cookiecutter.project_slug }}_production_flower
    ports:
      - "5555:5555"
    command: /flower
  {%- endif %}

  postgres:
    build:  ./docker/postgres/
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  redis:
    build: ./docker/redis/
    volumes:
      - production_redis_data:/data

  caddy:
    build:  ./docker/caddy/
    image: {{ cookiecutter.project_slug }}_production_caddy
    depends_on:
      - django
    volumes:
      - production_caddy:/root/.caddy
    env_file:
      - ./.envs/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
