#!/bin/bash

# creating user. Default ist user=docker, pass=changeme
# can be changed by setting ENV Variables SFTP_USER, SFTP_PASS
user="${SFTP_USER}"
pass="${SFTP_PASS}"

if [ "${PASS_ENCRYPTED}" == "true" ]; then
    chpasswdOptions="-e"
fi

useraddOptions="--create-home --shell /bin/bash"

if [ -n "${USER_UID}" ]; then
    useraddOptions="$useraddOptions --non-unique --uid ${USER_UID}"
fi

if [ -n "${USER_GID}" ]; then
    useraddOptions="$useraddOptions --gid ${USER_GID}"
    groupadd --gid ${USER_GID} ${USER_GID}
fi

useradd $useraddOptions $user

mkdir /home/$user/.ssh
cat /ssh_id_rsa.pub > /home/$user/.ssh/authorized_keys

chown $user:$user /home/$user
chmod 755 /home/$user
chmod 700 /home/$user/.ssh
chmod 700 /home/$user/.ssh
chmod 600 /home/$user/.ssh/authorized_keys

chown -R $user:$user /home/$user/

if [ -z "$pass" ]; then
    pass="$(echo `</dev/urandom tr -dc A-Za-z0-9 | head -c256`)"
    chpasswdOptions=""
fi

echo "$user:$pass" | chpasswd $chpasswdOptions

# starting ssh (detached)
exec /etc/init.d/ssh start &

exec "$@"
