#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
{%- if cookiecutter.use_async %}
/usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker -e DJANGO_SETTINGS_MODULE=config.settings.local --reload
{%- else %}
python manage.py runserver_plus 0.0.0.0:8000
{% endif %}
