#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py migrate
{%- if cookiecutter.use_async == 'y' %}
exec uvicorn config.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'
{%- else %}
exec python manage.py runserver_plus 0.0.0.0:8000
{%- endif %}
