version: '2'
services:
  postgres:
    build: ./compose/postgres
    volumes:
      # If you are using boot2docker, postgres data has to live in the VM for now until #581 is fixed
      # for more info see here: https://github.com/boot2docker/boot2docker/issues/581
      - /data/dev/{{cookiecutter.repo_name}}/postgres:/var/lib/postgresql/data
      - /data/dev/{{cookiecutter.repo_name}}/postgres-backups:/backups
    environment:
      - POSTGRES_USER={{cookiecutter.repo_name}}

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: python /app/manage.py runserver_plus 0.0.0.0:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER={{cookiecutter.repo_name}}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
{% if cookiecutter.use_pycharm == 'y' %}
  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER={{cookiecutter.repo_name}}
    volumes:
      - .:/app
    links:
      - postgres
{% endif %}
