# Creates a new issue for Major/Minor Django updates that keeps track
# of all dependencies that need to be updated/merged in order for the
# latest Django version to also be merged.
name: Django Issue Checker

on:
  schedule:
    - cron: "28 5 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  issue-checker:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'cookiecutter'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: "true"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Create Django Major Issue
        run: uv run scripts/create_django_issue.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
