# Creates a new issue for Major/Minor Django updates that keeps track
# of all dependencies that need to be updated/merged in order for the
# latest Django version to also be merged.
name: Django Issue Checker

on:
  schedule:
    - cron: "28 5 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  issue-checker:
    # Disables this workflow from running in a repository that is not part of the indicated organization/user
    if: github.repository_owner == 'cookiecutter'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create Django Major Issue
        run: python scripts/create_django_issue.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
