name: Update Licenses

on:
  # Every day at 2am
  schedule:
    - cron: "0 2 * * *"
  # Manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update list
        run: python scripts/update_licenses.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.1
        with:
          commit_message: Update Licenses
          file_pattern: cookiecutter.json {{cookiecutter.project_slug}}/licenses/*.txt
